version: '3'
services:
  frontend:
    image: frontend-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend-image:latest
    ports:
      - "3002:3002"
    restart: always
